# Generated by Django 5.2.8 on 2025-11-21 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metodopago',
            old_name='usuario',
            new_name='id_usuario',
        ),
    ]
