# Generated by Django 5.2.8 on 2025-11-21 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_usuario_metodopago_id_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='categoria',
            new_name='id_categoria',
        ),
    ]
