# Generated by Django 5.2.8 on 2025-11-24 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_categoria_producto_id_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='ciudad',
        ),
    ]
