# Generated by Django 5.2.8 on 2025-11-24 22:53

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_usuario_ciudad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='pais',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
