# Generated by Django 5.2.8 on 2025-11-26 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_etiqueta_producto_etiquetas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='etiquetas',
        ),
        migrations.AddField(
            model_name='producto',
            name='etiqueta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.etiqueta'),
        ),
    ]
