# Generated by Django 5.2.8 on 2025-11-26 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_producto_etiquetas_producto_etiqueta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='etiqueta',
        ),
        migrations.AddField(
            model_name='producto',
            name='etiquetas',
            field=models.ManyToManyField(blank=True, to='core.etiqueta'),
        ),
    ]
