# Generated by Django 5.2.8 on 2025-11-29 22:14

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_producto_etiqueta_producto_etiquetas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carritodetalle',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='carritodetalle',
            name='carrito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carritodetalle_set', to='core.carrito'),
        ),
        migrations.AlterField(
            model_name='carritodetalle',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.producto'),
        ),
        migrations.AlterField(
            model_name='carritodetalle',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterUniqueTogether(
            name='carritodetalle',
            unique_together={('carrito', 'producto')},
        ),
        migrations.CreateModel(
            name='MetodoPagoUsuario',
            fields=[
                ('id_metodo', models.AutoField(primary_key=True, serialize=False)),
                ('stripe_payment_method_id', models.CharField(max_length=255, unique=True)),
                ('marca', models.CharField(max_length=50)),
                ('ultimos_4', models.CharField(max_length=4)),
                ('vencimiento', models.CharField(max_length=5)),
                ('es_principal', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metodos_pago_stripe', to='core.usuario')),
            ],
            options={
                'ordering': ['-es_principal', '-creado_en'],
            },
        ),
        migrations.AlterField(
            model_name='factura',
            name='metodo_pago',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.metodopagousuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='metodo_pago_preferido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_prefieren', to='core.metodopagousuario'),
        ),
        migrations.DeleteModel(
            name='MetodoPago',
        ),
    ]
