# Generated by Django 5.2.8 on 2025-11-29 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_carritodetalle_cantidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
