# Generated by Django 5.2.8 on 2025-11-30 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_usuario_stripe_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entregaclave',
            name='fecha_entrega',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
