# Generated by Django 5.2.8 on 2025-11-30 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_entregaclave_fecha_entrega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clavejuego',
            name='clave',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
