# Generated by Django 5.2.8 on 2025-11-30 03:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_clavejuego_clave'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clavejuego',
            options={'ordering': ['-fecha_creacion']},
        ),
        migrations.AddField(
            model_name='clavejuego',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clavejuego',
            name='factura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claves_entregadas', to='core.factura'),
        ),
        migrations.AlterField(
            model_name='clavejuego',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claves', to='core.producto'),
        ),
    ]
