# Generated by Django 5.2.8 on 2025-11-30 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_clavejuego_options_clavejuego_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clavejuego',
            unique_together={('producto', 'clave')},
        ),
    ]
