from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('crear-cuenta/', views.crear_cuenta, name='crear_cuenta'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('perfil-usuario/', views.perfil_usuario, name='perfil_usuario'),
    path('api/actualizar-perfil/', views.actualizar_perfil, name='actualizar_perfil'),
    path('perfil-cliente/', views.perfil_cliente, name='perfil_cliente'),
    path('perfil-cliente/<int:cliente_id>/', views.perfil_cliente, name='perfil_cliente'),
    path('anadir-juegos/', views.anadir_juegos, name='anadir_juegos'),
    path('eliminar-producto/<int:id_producto>/', views.eliminar_producto, name='eliminar_producto'),
    path('pago/', views.pago, name='pago'),
    path('factura/<int:factura_id>/', views.confirmacion_compra, name='factura'),
    path('reporte-factura/', views.reporte_factura, name='reporte_factura'),
    path('reporte-ventas/', views.reporte_ventas, name='reporte_ventas'),
    path('listado-clientes/', views.listado_clientes, name='listado_clientes'),
    path('actualizar-etiqueta/<int:id_producto>/', views.actualizar_etiqueta, name='actualizar_etiqueta'),
    path('api/productos/', views.api_productos, name='api_productos'),
    path('api/cart/add/', views.api_add_to_cart, name='api_cart_add'),
    path('api/cart/', views.api_get_cart, name='api_get_cart'),
    path('api/cart/remove/', views.api_remove_from_cart, name='api_cart_remove'),
    path('api/cart/update/', views.api_update_cart, name='api_cart_update'),
    path('api/payment-methods/', views.api_get_payment_methods, name='api_payment_methods'),
    path('api/payment-methods/add/', views.api_create_payment_method, name='api_add_payment_method'),
    path('api/payment-methods/delete/', views.api_delete_payment_method, name='api_delete_payment_method'),
    path('api/payment-methods/primary/', views.api_set_primary_payment_method, name='api_set_primary_payment_method'),
    path('api/process-payment/', views.api_process_payment, name='api_process_payment'),
    path('confirmacion-compra/<int:factura_id>/', views.confirmacion_compra, name='confirmacion_compra'),
    path('api/purchase-history/', views.purchase_history_api, name='api_purchase_history'),
    path('api/profile/change-password/', views.api_change_password, name='api_change_password'),
    path('panel-admin/', views.panel_admin, name='panel_admin'),
]
